/**
 * AUTO-GENERATED FILE @ Tue, 17 May 2022 11:10:40 GMT - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.1.0.4
 * $ schemats generate postgres://username:password@localhost:5432/foodplanner -C -s public
 *
 */

export interface Ingredient {
  id: string
  name: string
  inventoryAmount?: number | null
  inventoryUnitId?: number | null
  createdAt?: Date | null
  updatedAt: Date
}

export interface Unit {
  id: number
  name: string
  createdAt?: Date | null
  updatedAt: Date
}

export interface Tables {
  ingredients: Ingredient
  units: Unit
}
